# 项目端口号
port: '4001'
# 服务器配置
data_base:
  # 服务器地址
  host: '127.0.0.1'
  # 服务器端口
  port: '3306'
  # 用户名
  user_name: 'root'
  # 密码
  password: '555555'
  # 数据库名
  schema: 'gin_co_blog'
# 日志配置
log_config:
  # 日志存储位置
  path: 'logs/'
  # 日志名称
  name: 'gin.log'
