# 项目端口号
port: '4001'
# 服务器配置
data_base:
  # 服务器地址
  host: '127.0.0.1'
  # 服务器端口
  port: '3306'
  # 用户名
  user_name: 'root'
  # 密码
  password: '555555'
  # 数据库名
  schema: 'gin_co_blog'
# 日志配置
log_config:
  # 日志存储位置
  path: 'logs/'
  # 日志名称
  name: 'gin.log'
# 正则
regular:
  # 电话号码正则
  phone: '^(13[0-9]|14[5-9]|15[0-35-9]|16[6]|17[0-8]|18[0-9]|19[0-9]|147|166|17[0-1]|162)\d{8}$'
  # 邮箱正则
  email: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
# 邮箱配置
email_config:
  # 邮箱地址
  email_address: 'co-blog@qq.com'
  # 邮箱名
  email_name: 'CoBlog站长'
  # 邮箱密码
  password: 'qgiegwujfquqbjfd'
  # 邮箱服务器
  smtp_server: 'smtp.qq.com'
  # 邮箱端口
  smtp_port: 587
# redis
redis_config:
  host: '127.0.0.1'
  port: '6379'
  password: ''
  db: 0
# 加密
encryption:
  # 私钥
  private_key:
    password: '1b6b260b-67d1-4b5a-917e-10ec233329ca'
  # 盐值
  salt:
    password: 10
# token 配置
token:
  private_key: 'af28c9fe-9426-41dd-8ea7-cba762ec0f1e'
# 不验证的接口地址
not_verify_url:
  - '/api/user/phoneOccupy'
  - '/api/user/emailOccupy'
  - '/api/user/register'
  - '/api/user/phoneLogin'
  - '/api/user/emailLogin'
  - '/api/user/sendEmailCode'
  - '/api/user/forgotPassword'
# 跨域IP
cors:
  ip:
    - 'http://127.0.0.1'
    - 'http://39.101.72.168'
    - 'http://localhost'
  methods:
    - 'GET'
    - 'POST'
    - 'PUT'
    - 'DELETE'
